### ISSUE TITLE
11 y 14.  (11)Diferenciar los tipos de hora con un código, para poder sacar luego los listados y los resúmenes.(14). Poder insertar en la ficha de cada trabajador el coste hora del trabajador, y luego según ese coste calcular el coste hora real según los trabajadores que han realizado el trabajo.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/Serbusa#11]
En principio esta todo bien, pero voy a hacer alguna prueba mas, dando de alta y baja más partes.

![ScreenClip.png](https://zube.io/files/gregorioruiz/fd63ca84ce430ed5c8c617fda3f079a5.png)

![ScreenClip.png](https://zube.io/files/gregorioruiz/5b22b780298ee96485253a99cbf6cc75.png)

![ScreenClip.png](https://zube.io/files/gregorioruiz/aad6e49a74155707d6744be986da3a86.png)

**Comment by gregorioruiz** [comment]
Para recalcular ahora los trabajos o en cualquier momento en que se revisen estos datos, he puesto un proceso en la lista de trabajadores que los baja a los partes del ejercicio.

![ScreenClip.png](https://zube.io/files/gregorioruiz/f71f54ce26a59536261d35945c846695.png)

Pensar si puede ser necesario preguntar además una fecha desde o fechas desde-hasta.

**Comment by gregorioruiz** [comment]
11 y 14- prueba: Coger su copia de seguridad, probar y preparar los procesos de actualización y cambios durante el ejercicio o al acabar el año y hacer el estudio.

**Comment by gregorioruiz** [comment]
Ya tengo la copia de seguridad y el vam que funciona en su equipo.
Restaurar con esos datos, poner encima el actual y ver si hace todo lo necesario para recuperar la información.
Sobre todo, tengo que poner mucha atención a la valoración de los trabajos, pues me puedo quedar a cero hasta que metan datos en los trabajadores, etc.

**Comment by gregorioruiz** [comment]
El cálculo de coste real horas, se hace multiplicando las horas reales por el precio hora que figura en el trabajo.
Como ahora esto se cambia, hacer un proceso inicial que cargue este valor en todas las líneas de parte para que quede como está.
Luego ya cambiarán y recalcularán los ejercicios que quieran.

![ScreenClip.png](https://zube.io/files/gregorioruiz/e85fef3e6062c3f05604e3ed1ae58da0.png)

**Comment by gregorioruiz** [comment]
Hecha la carga inicial. Acabar de comprobar lo del principio y pensar si con eso pueden tener bien valorados los trabajos.

**Comment by gregorioruiz** [comment]
Ya funciona. Había previsto mal el tamaño del dato y con 800 euros en sólo día por trabajador se le fundían los cálculos.

**Comment by anacid** [comment]
Ok funciona. He probado a poner en un trabajador un precio de hora, he recalculado los partes del ejercicio, he ido al trabajo y ya pone el precio de hora y el total coste está bien.
