### ISSUE TITLE
12. Poder adjuntar archivos y documentos en las ficha del cliente y del proveedor.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/Serbusa#12]
![ScreenClip.png](https://zube.io/files/gregorioruiz/05e5970480c5c1fd8b1323d55ca91aeb.png)

![ScreenClip.png](https://zube.io/files/gregorioruiz/6b64bbbfe8909ed6339b2450bcfee611.png)

**Comment by gregorioruiz** [comment]
He ocultado el botón de hacer FTP, el de abajo del todo, cuando la ficha ya está creada. Esto bloquearía una recarga por error del fichero con otro. Pero también impide actualizarle.
Acabar de pensar y repasar tanto clientes como proveedores.

**Comment by anacid** [comment]
Repasado tanto en clientes como en proveedores, y no puedo subir bien los documentos ni verlos.
Dejo la imagen en el evernote "Serbusa - fecha 14-10-2015", en el punto 12.

**Comment by anacid** [comment]
![ScreenClip.png](https://zube.io/files/gregorioruiz/efebb00a57ca0eb65132fbdfe56f18f6.png)

**Comment by anacid** [comment]
![ScreenClip.png](https://zube.io/files/gregorioruiz/d2fd86b9d189e2209a3172be63318aea.png)

**Comment by anacid** [comment]
curioso pero esta vez si he podido subir las imágenes.

**Comment by gregorioruiz** [comment]
A mi me funciona. Ya sé que a ti te va a fallar. 
También puedo añadir un documento en presupuestos.
