### ISSUE TITLE
15. Añadir más caracteres en la ficha del cliente, los códigos postales no te deja poner códigos extranjeros y la dirección 2 no sale cuando imprimes una factura o un presupuesto.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/Serbusa#15]
Copiar del monte carmelo.
![ScreenClip.png](https://zube.io/files/gregorioruiz/adbaf932a16c6b9a748fd786e1a415f3.png)
![ScreenClip.png](https://zube.io/files/gregorioruiz/b9ea00ef53461d63377e2d153b882cbf.png)

**Comment by gregorioruiz** [comment]
Hecho en un proceso de actualización el cambio del Cod. postal

La dirección2, hay que cambiarla en todos estos informes

![ScreenClip.png](https://zube.io/files/gregorioruiz/211f090ec65877d1ae363b5c57ccd0bd.png)

**Comment by gregorioruiz** [comment]
Hecho. Comprobar alguno, pero no si no, ya lo harán ellos.

**Comment by anacid** [comment]
1.- En albaranes, tanto en imprimir en papel como en pdf, si aparece la segunda dirección y el codigo postal largo.
2.- En facturas, idem
3.- En presupuesto, idem
Lo damos por comprobado. 
OK
