### ISSUE TITLE
16. Que la letra de los presupuesto cuando se imprime sea más grande, y el título no quede tan pegado arriba.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/Serbusa#16]

**Comment by gregorioruiz** [comment]
**Hecho en el Imprimir presupuesto (sin iva)** 

No me gusta cómo gestiona las rayas pues aparecen ahora muchos más espacios sin pintar.

![ScreenClip.png](https://zube.io/files/gregorioruiz/6f2085eb599371ad0c9216043958d0b8.png)

**Comment by gregorioruiz** [comment]
(16) Imprimir presupuesto en pdf con uno y otro formato y mandárselo para que den el visto bueno antes de hacer todos los informes.

**Comment by anacid** [comment]
Pendiente que nos confirmen si así les gusta la letra, para cambiar en el resto de los informes.

**Comment by gregorioruiz** [comment]
Ok a lo que mandamos.
