### ISSUE TITLE
2. En los presupuestos, añadir las condiciones.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/Serbusa#2]
- Hecho en el portatil en el directorio c:\adolix. Habrá que ver como ponerlo en el directorio donde estén las facturas y el pdf de las condciones.
- Pruebas y desarrollo de cómo y dónde instalar y cómo pasar el comando.

**Comment by gregorioruiz** [comment]
Instalar Adolixpdf en un directorio donde estén las facturas y el pdf de condiciones

Crear allí un .bat con esta línea
adolixsplitandmergepdf.exe -qm uno.pdf dos.pdf -o tres.pdf

Al ejecutar este bat, se crea el fichero tres.pdf con la unión de los dos primeros sin mensajes en pantalla.

Una vez instalado el adolix, parece que basta con copiar el contenido del directorio a todas las carpetas donde haya que mezclar ficheros para que funcione y las instrucciones en velneo sean más sencillas.

**Comment by gregorioruiz** [comment]
Me vuelvo a pegar con el hecho de que los informes, como son un retorno, se ejecutan en los procesos al final del todo. 
Por tanto, no volver a perder el tiempo y poner en el menú otra entrada de adjuntar condiciones entre imprimir y archivar.

**Comment by anacid** [comment]
No puedo probarlo en mi ordenador porque no me funciona, ni tan siquiera figura en ficheros. Por lo que tampoco puedo enviarlo por e-mail

**Comment by gregorioruiz** [comment]
voy

El 15 de octubre de 2015, 13:09, anacid notifications@github.com escribió:

> No puedo probarlo en mi ordenador porque no me funciona, ni tan siquiera
> figura en ficheros. Por lo que tampoco puedo enviarlo por e-mail
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gregorioruiz/Serbusa/issues/2#issuecomment-148354379.

## 

Un saludo,

Gregorio Ruiz Vecino
Cid Multimedia S.L.

**Comment by anacid** [comment]
Ok, probado y funciona
