### ISSUE TITLE
Trabajos-partes-tipo de hora

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/Serbusa#25]
Cambiar la rejilla para que se pueda ver el tipo de hora. Hacer más pequeño el comentario.

![ScreenClip.png](https://zube.io/files/gregorioruiz/979de842813cfb78c55d0c2e1f9bc37a.png)

**Comment by anacid** [comment]
Ok, creo que se lo podemos poner y que ella lo prueba, yo ya lo he visto.
