### ISSUE TITLE
Categorías de trabajador

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/Serbusa#28]
Hola Ana,

Categorias por trabajador:
·         Oficial 1ª, 2ª y 3ª.

·         Especialista.

·         Encargado.

·         Ingeniero.

Un saludo.

**Comment by anacid** [comment]
Ahora en la pantalla de Trabajadores, está "categorías", estas categorías practicamente las usan para hacer presupuestos, aquí Raquel no toca nada.
Me dice que si estas "categorias", podemos pasarlas a "presupuesto".
Y en trabajadores, dejarla para las categorías nuevas, con los precios por hora para los partes.
De todas formas lo vemos para ver como lo podemos definir bien.

![ScreenClip.png](https://zube.io/files/gregorioruiz/0321f166bf305f9c0b7f781da43208d8.png)
![ScreenClip.png](https://zube.io/files/gregorioruiz/a1e767d7b1c585cd60bd7e79543cfed0.png)
![ScreenClip.png](https://zube.io/files/gregorioruiz/15e1617cd8b5d5e41e670712bf86f471.png)

**Comment by gregorioruiz** [comment]
He pasado esa lista de categorías a Presupuestos.
He creado al nueva en trabajadores y hecho el proceso para que actualice.

![ScreenClip.png](https://zube.io/files/gregorioruiz/5a2eb986c3924745f513e0963327abc1.png)

![ScreenClip.png](https://zube.io/files/gregorioruiz/83e19305f254c832809e5ca4fc342d14.png)

![ScreenClip.png](https://zube.io/files/gregorioruiz/591c8cfd20e6d088c90eef210c6d0d45.png)

**Comment by anacid** [comment]
Ya puestos en gastos, cuando entramos en categorías, pone "Bancos", no te adjunto la pantalla porque está en cualquiera de los pantallazos anteriores.

**Comment by anacid** [comment]
Lo he probado, he dado de alta categorías, las he actualizado en trabajadores, y he hecho el proceso de actualizar las horas, y lo hace bien.

**Comment by anacid** [comment]
Simplemente creo que debemos de modificar en lugar de "tipo de hora", creo que debiera de poner "tipo de categoría"
![ScreenClip.png](https://zube.io/files/gregorioruiz/a501f6f10463451977fec31b3d141145.png)
