### ISSUE TITLE
8. Poder añadir en los presupuestos el importe con IVA, porque algunas veces nos lo piden.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/Serbusa#8]
- Siempre es el tipo de IVA normal.

![ScreenClip.png](https://zube.io/files/gregorioruiz/fe6977f070e86ce56c4906899d65641f.png)

![ScreenClip.png](https://zube.io/files/gregorioruiz/0a3fa63f5abee1cb574e15c003938d7c.png)

**Comment by gregorioruiz** [comment]
Ya he cambiado los botones del menú imprimir presupuesto, para que salgan sólo los nuevos informes que sí que controla lo del iva.

![ScreenClip.png](https://zube.io/files/gregorioruiz/457faad92d9e916027930cdeb4f2c12f.png)

**Comment by anacid** [comment]
Ok, probado y funciona
