### ISSUE TITLE
9. Poner en las facturas el código del proveedor y el nº de albarán y fecha del albarán

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/Serbusa#9]
![ScreenClip.png](https://zube.io/files/gregorioruiz/3da038def316d4bfd801543cb926c906.png)
![ScreenClip.png](https://zube.io/files/gregorioruiz/6e9495d18c09137a670fd2ccf55569db.png)

Una vez generada la factura, damos a imprimir "Imprimir" 

![ScreenClip.png](https://zube.io/files/gregorioruiz/97728fedd9f04814ded2ad1b3763d57b.png)

y vuelvo a imprimir la misma factura pero esta vez "Imprimir en pdf"

![ScreenClip.png](https://zube.io/files/gregorioruiz/e662a7b1f2b7c468fd86249a4db956c2.png)

**Comment by anacid** [comment]
Ok a: código de proveedor, nº de albarán y fecha de albarán, pero tenemos que mover el texto queda todo un poco amontonado.

**Comment by anacid** [comment]
Como no consigo adjuntar la imagen, en evernote en la carpeta "0-trabajos a goyo", en "Serbusa - fecha 14-10-2015", he dejado la imagen marcada como el apartado 9.

**Comment by gregorioruiz** [comment]
Hecho (creo)
